name: Build Docker

on: pull_request

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v4

      - name: 'Build image'
        run: |
          docker build . --build-arg GITHASH=${{ github.sha }} --build-arg BUILDTAG=${{ github.run_id }}
