name: Build Docker

on: pull_request

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v4\

      - uses: ./.github/workflows/parts/cache/
      - name: 'Create the template'
        run: |
          dotnet build
        working-directory: ./template/

      - name: 'Build image'
        run: |
          docker build . --build-arg GITHASH=${{ github.sha }} --build-arg BUILDTAG=${{ github.run_id }}
        working-directory: ./template/content/complete/
